# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ramANDrom/ramANDrom.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom || ORIG_REF_NAME==ramANDrom}]

# IP: bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_0/ramANDrom_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_blk_mem_gen_0_0 || ORIG_REF_NAME==ramANDrom_blk_mem_gen_0_0}]

# IP: bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_1/ramANDrom_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_blk_mem_gen_0_1 || ORIG_REF_NAME==ramANDrom_blk_mem_gen_0_1}]

# IP: bd/ramANDrom/ip/ramANDrom_xlconcat_0_0/ramANDrom_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_xlconcat_0_0 || ORIG_REF_NAME==ramANDrom_xlconcat_0_0}]

# IP: bd/ramANDrom/ip/ramANDrom_xlslice_0_0/ramANDrom_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_xlslice_0_0 || ORIG_REF_NAME==ramANDrom_xlslice_0_0}]

# IP: bd/ramANDrom/ip/ramANDrom_xlslice_0_1/ramANDrom_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_xlslice_0_1 || ORIG_REF_NAME==ramANDrom_xlslice_0_1}]

# IP: bd/ramANDrom/ip/ramANDrom_xlslice_0_2/ramANDrom_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_xlslice_0_2 || ORIG_REF_NAME==ramANDrom_xlslice_0_2}]

# IP: bd/ramANDrom/ip/ramANDrom_xlslice_0_3/ramANDrom_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ramANDrom_xlslice_0_3 || ORIG_REF_NAME==ramANDrom_xlslice_0_3}]

# XDC: bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_0/ramANDrom_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_1/ramANDrom_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/ramANDrom/ramANDrom_ooc.xdc
