# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.cache/wt [current_project]
set_property parent.project_path /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom [current_project]
add_files /media/psf/Home/Development/ect_ua/cr-final-project/Memoria/8words_16bits.coe
add_files /media/psf/Home/Development/ect_ua/cr-final-project/Repository/Memoria/8words_16bits.coe
add_files /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/8words_16bits.coe
add_files /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/ramANDrom.bd
set_property used_in_implementation false [get_files -all /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_0/ramANDrom_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/ip/ramANDrom_blk_mem_gen_0_1/ramANDrom_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/ramANDrom_ooc.xdc]
set_property is_locked true [get_files /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/ramANDrom.bd]

read_verilog -library xil_defaultlib /media/psf/Home/Development/ect_ua/cr-final-project/Repository/ramANDrom/ramANDrom/ramANDrom.srcs/sources_1/bd/ramANDrom/hdl/ramANDrom_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ramANDrom_wrapper -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ramANDrom_wrapper.dcp

catch { report_utilization -file ramANDrom_wrapper_utilization_synth.rpt -pb ramANDrom_wrapper_utilization_synth.pb }
