# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir I:/SDR_P/10/UserDefinedRepository/Iterative_sorter_final/Iterative_sorter_final.cache/wt [current_project]
set_property parent.project_path I:/SDR_P/10/UserDefinedRepository/Iterative_sorter_final/Iterative_sorter_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib I:/SDR_P/10/UserDefinedRepository/Iterative_sorter_final/Iterative_sorter_final.srcs/sources_1/new/Top_iterative_sorter.vhd
catch { write_hwdef -file IterativeSorterFSM.hwdef }
synth_design -top IterativeSorterFSM -part xc7a100tcsg324-1
write_checkpoint -noxdef IterativeSorterFSM.dcp
catch { report_utilization -file IterativeSorterFSM_utilization_synth.rpt -pb IterativeSorterFSM_utilization_synth.pb }
